@startuml
'https://plantuml.com/class-diagram


class Solution43{
+{static} void main()
+boolean checkString()
-String getInput(String prompt)
}
class SiteBuilder{
-final String siteName
-final String author
-final boolean jsFolder
-final boolean cssFolder
-final String SITE_FOLDER_NAME

+SiteBuilder(String siteName, String author, boolean jsFolder, boolean cssFolder
+void buildWebsite()
-void createHTMLFile(String contents)
-void createFolder(String name)
-String populateHTML()
}

Solution43 -- SiteBuilder
@enduml