@startuml
'https://plantuml.com/class-diagram

class Solution41{
+{static} main()
}
class NameSorter{
+addNamesToList(List<String> names, Scanner input): List<String>
+sortNamesInList(List<String> names): List<String>
+printSortedNamesToFile(List<String> names)
}

Solution41 --o NameSorter
@enduml