@startuml
'https://plantuml.com/class-diagram

class Solution41{
+{static} main()
}
class NameSorter{
+List<String> addNamesToList(List<String> names, Scanner input)
+List<String> sortNamesInList(List<String> names)
+void printSortedNamesToFile(List<String> names)
}

Solution41 --o NameSorter
@enduml