@startuml
'https://plantuml.com/class-diagram

class Solution45{
+{static} void main
}

class WordReplacer{
-ArrayList<String> sentence
-String filePath
-String outputFileName
+WordReplacer(String filePath, String outputFileName)
+void replaceWord(String replacedWord, String replaceWith)
-ArrayList<String> readFile()
-void writeFile()
-void printSentence(String io)
}

Solution45 -- WordReplacer

@enduml